-- =====================================================
-- APEX GYM — Migración inicial
-- 001_initial_schema.sql
--
-- Ejecutable sobre una base PostgreSQL vacía.
-- Deriva del modelo lógico congelado: database/schema.dbml
--
-- Alcance: solo estructura (tablas, PK, FK, UNIQUE, índices).
-- Sin ENUM, CHECK de negocio, triggers, funciones, vistas ni RLS:
-- esas reglas son responsabilidad del backend.
-- =====================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- =====================================================
-- Plataforma
-- =====================================================

CREATE TABLE platform_admins (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email      VARCHAR UNIQUE,
    password   VARCHAR(255),
    full_name  VARCHAR,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    state      INTEGER
);

CREATE TABLE companies (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            TEXT,
    legal_name      TEXT,
    currency        VARCHAR(3),
    timezone        TEXT,
    created_by      UUID REFERENCES platform_admins (id),
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW(),
    logo_path       TEXT,
    primary_color   TEXT,
    secondary_color TEXT,
    accent_color    TEXT
);


-- =====================================================
-- Seguridad
-- =====================================================

CREATE TABLE roles (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  UUID REFERENCES companies (id),
    name        VARCHAR,
    description VARCHAR,
    state       INTEGER,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_roles_company_name UNIQUE (company_id, name)
);

CREATE TABLE modules (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR UNIQUE,
    description VARCHAR,
    state       INTEGER
);

CREATE TABLE permissions (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id   INTEGER REFERENCES modules (id),
    action      VARCHAR,
    code        VARCHAR UNIQUE,
    description VARCHAR
);

CREATE TABLE users (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID REFERENCES companies (id),
    username   VARCHAR,
    full_name  VARCHAR(150),
    password   VARCHAR(255),
    role_id    INTEGER REFERENCES roles (id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    state      INTEGER,
    CONSTRAINT uq_users_company_username UNIQUE (company_id, username)
);

CREATE TABLE role_permissions (
    role_id       INTEGER REFERENCES roles (id),
    permission_id INTEGER REFERENCES permissions (id),
    granted_at    TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (role_id, permission_id)
);


-- =====================================================
-- Clientes
-- =====================================================

CREATE TABLE clients (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id              UUID NOT NULL REFERENCES companies (id),
    document_number         VARCHAR(50) NOT NULL,
    full_name               VARCHAR(150) NOT NULL,
    phone                   VARCHAR(30),
    email                   VARCHAR(150),
    emergency_contact_name  VARCHAR(150),
    emergency_contact_phone VARCHAR(30),
    blood_type              VARCHAR(5),
    birth_date              DATE,
    medical_condition       TEXT,
    comments                TEXT,
    state                   INTEGER NOT NULL DEFAULT 1,
    registered_at           DATE NOT NULL,
    retired_at              TIMESTAMPTZ,
    created_by              UUID REFERENCES users (id),
    created_at              TIMESTAMPTZ DEFAULT NOW(),
    updated_at              TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_clients_company_document UNIQUE (company_id, document_number)
);

CREATE INDEX idx_clients_company_state    ON clients (company_id, state);
CREATE INDEX idx_clients_company_fullname ON clients (company_id, full_name);

CREATE TABLE client_notes (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL REFERENCES companies (id),
    client_id  UUID NOT NULL REFERENCES clients (id),
    note       TEXT NOT NULL,
    created_by UUID REFERENCES users (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_client_notes_client_created ON client_notes (client_id, created_at);


-- =====================================================
-- Membresías
-- =====================================================

CREATE TABLE membership_types (
    id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id             UUID NOT NULL REFERENCES companies (id),
    name                   VARCHAR(100) NOT NULL,
    price                  NUMERIC(12,2) NOT NULL,
    description            TEXT,
    duration_value         INTEGER NOT NULL,
    duration_unit          VARCHAR(20) NOT NULL,
    minimum_payment        NUMERIC(12,2),
    trainer_share          NUMERIC(12,2),
    business_share         NUMERIC(12,2),
    allows_partial_payment BOOLEAN NOT NULL DEFAULT FALSE,
    is_promotional         BOOLEAN NOT NULL DEFAULT FALSE,
    state                  INTEGER NOT NULL DEFAULT 1,
    created_at             TIMESTAMPTZ DEFAULT NOW(),
    updated_at             TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_membership_types_company_name UNIQUE (company_id, name)
);


-- =====================================================
-- Entrenadores
-- =====================================================

CREATE TABLE trainers (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id      UUID NOT NULL REFERENCES companies (id),
    full_name       VARCHAR(150) NOT NULL,
    document_number VARCHAR(50) NOT NULL,
    phone           VARCHAR(30),
    hired_at        DATE,
    salary          NUMERIC(12,2),
    max_clients     INTEGER,
    state           INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_trainers_company_document UNIQUE (company_id, document_number)
);

CREATE INDEX idx_trainers_company_state ON trainers (company_id, state);


-- =====================================================
-- Promociones de grupo
-- =====================================================

CREATE TABLE promotion_groups (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL REFERENCES companies (id),
    name       VARCHAR(100) NOT NULL,
    state      INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_promotion_groups_company_name ON promotion_groups (company_id, name);

CREATE TABLE promotion_group_members (
    promotion_group_id UUID NOT NULL REFERENCES promotion_groups (id),
    client_id          UUID NOT NULL REFERENCES clients (id),
    joined_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (promotion_group_id, client_id)
);

CREATE INDEX idx_promotion_group_members_client ON promotion_group_members (client_id);


-- =====================================================
-- Membresías de cliente
-- =====================================================

CREATE TABLE client_memberships (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id         UUID NOT NULL REFERENCES companies (id),
    client_id          UUID NOT NULL REFERENCES clients (id),
    membership_type_id UUID NOT NULL REFERENCES membership_types (id),
    trainer_id         UUID REFERENCES trainers (id),
    promotion_group_id UUID REFERENCES promotion_groups (id),
    start_date         DATE NOT NULL,
    end_date           DATE NOT NULL,
    agreed_price       NUMERIC(12,2) NOT NULL,
    state              INTEGER NOT NULL DEFAULT 1,
    created_by         UUID REFERENCES users (id),
    created_at         TIMESTAMPTZ DEFAULT NOW(),
    updated_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_client_memberships_client_start   ON client_memberships (client_id, start_date);
CREATE INDEX idx_client_memberships_company_state  ON client_memberships (company_id, state);
CREATE INDEX idx_client_memberships_company_end    ON client_memberships (company_id, end_date);
CREATE INDEX idx_client_memberships_trainer_state  ON client_memberships (trainer_id, state);
CREATE INDEX idx_client_memberships_promo_group    ON client_memberships (promotion_group_id);


-- =====================================================
-- Pagos
-- =====================================================

CREATE TABLE payments (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id           UUID NOT NULL REFERENCES companies (id),
    client_membership_id UUID NOT NULL REFERENCES client_memberships (id),
    amount               NUMERIC(12,2) NOT NULL,
    payment_type         VARCHAR(20) NOT NULL,
    payment_method       VARCHAR(20) NOT NULL,
    balance_after        NUMERIC(12,2) NOT NULL,
    paid_at              TIMESTAMPTZ NOT NULL,
    notes                TEXT,
    created_by           UUID REFERENCES users (id),
    created_at           TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_payments_membership_paid ON payments (client_membership_id, paid_at);
CREATE INDEX idx_payments_company_paid    ON payments (company_id, paid_at);


-- =====================================================
-- Comisiones de entrenadores
-- =====================================================

CREATE TABLE trainer_commissions (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id           UUID NOT NULL REFERENCES companies (id),
    trainer_id           UUID NOT NULL REFERENCES trainers (id),
    client_membership_id UUID NOT NULL REFERENCES client_memberships (id),
    payment_id           UUID NOT NULL UNIQUE REFERENCES payments (id),
    trainer_amount       NUMERIC(12,2) NOT NULL,
    business_amount      NUMERIC(12,2) NOT NULL,
    commission_date      DATE NOT NULL,
    created_at           TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_trainer_commissions_trainer_date ON trainer_commissions (trainer_id, commission_date);
CREATE INDEX idx_trainer_commissions_company_date ON trainer_commissions (company_id, commission_date);


-- =====================================================
-- Egresos
-- =====================================================

CREATE TABLE expense_categories (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id  UUID NOT NULL REFERENCES companies (id),
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    state       INTEGER NOT NULL DEFAULT 1,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_expense_categories_company_name UNIQUE (company_id, name)
);

CREATE TABLE expenses (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id   UUID NOT NULL REFERENCES companies (id),
    category_id  UUID NOT NULL REFERENCES expense_categories (id),
    concept      VARCHAR(200) NOT NULL,
    amount       NUMERIC(12,2) NOT NULL,
    expense_date DATE NOT NULL,
    created_by   UUID REFERENCES users (id),
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_expenses_company_date ON expenses (company_id, expense_date);
CREATE INDEX idx_expenses_category     ON expenses (category_id);


-- =====================================================
-- Inventario
-- =====================================================

CREATE TABLE inventory_items (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id      UUID NOT NULL REFERENCES companies (id),
    name            VARCHAR(150) NOT NULL,
    description     TEXT,
    unit_of_measure VARCHAR(30) NOT NULL,
    current_stock   NUMERIC(12,3) NOT NULL DEFAULT 0,
    minimum_stock   NUMERIC(12,3) NOT NULL DEFAULT 0,
    state           INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_inventory_items_company_name UNIQUE (company_id, name)
);

CREATE INDEX idx_inventory_items_company_state ON inventory_items (company_id, state);

CREATE TABLE inventory_movements (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id        UUID NOT NULL REFERENCES companies (id),
    inventory_item_id UUID NOT NULL REFERENCES inventory_items (id),
    movement_type     VARCHAR(20) NOT NULL,
    quantity          NUMERIC(12,3) NOT NULL,
    previous_stock    NUMERIC(12,3),
    resulting_stock   NUMERIC(12,3),
    reason            TEXT,
    created_by        UUID REFERENCES users (id),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_inventory_movements_item_created    ON inventory_movements (inventory_item_id, created_at);
CREATE INDEX idx_inventory_movements_company_created ON inventory_movements (company_id, created_at);

CREATE TABLE equipment_maintenance (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id        UUID NOT NULL REFERENCES companies (id),
    inventory_item_id UUID NOT NULL REFERENCES inventory_items (id),
    scheduled_date    DATE NOT NULL,
    completed_date    DATE,
    description       TEXT,
    state             INTEGER NOT NULL DEFAULT 1,
    created_by        UUID REFERENCES users (id),
    created_at        TIMESTAMPTZ DEFAULT NOW(),
    updated_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_equipment_maintenance_item_scheduled ON equipment_maintenance (inventory_item_id, scheduled_date);
CREATE INDEX idx_equipment_maintenance_company_state  ON equipment_maintenance (company_id, state);


-- =====================================================
-- Operación
-- =====================================================

CREATE TABLE daily_logs (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id   UUID NOT NULL REFERENCES companies (id),
    log_date     DATE NOT NULL,
    observations TEXT,
    created_by   UUID REFERENCES users (id),
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_daily_logs_company_date UNIQUE (company_id, log_date)
);

CREATE TABLE monthly_closures (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id   UUID NOT NULL REFERENCES companies (id),
    year         INTEGER NOT NULL,
    month        INTEGER NOT NULL,
    observations TEXT,
    closed_by    UUID REFERENCES users (id),
    closed_at    TIMESTAMPTZ,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_monthly_closures_company_year_month UNIQUE (company_id, year, month)
);


-- =====================================================
-- Asistencia
-- =====================================================

CREATE TABLE attendances (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL REFERENCES companies (id),
    client_id  UUID NOT NULL REFERENCES clients (id),
    check_in   TIMESTAMPTZ NOT NULL,
    check_out  TIMESTAMPTZ,
    source     VARCHAR(20) NOT NULL DEFAULT 'manual',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_attendances_client_checkin  ON attendances (client_id, check_in);
CREATE INDEX idx_attendances_company_checkin ON attendances (company_id, check_in);

CREATE TABLE client_biometrics (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id         UUID NOT NULL REFERENCES companies (id),
    client_id          UUID NOT NULL REFERENCES clients (id),
    external_reference VARCHAR(150),
    provider           VARCHAR(50),
    state              INTEGER NOT NULL DEFAULT 1,
    created_at         TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_client_biometrics_company_provider_ref UNIQUE (company_id, provider, external_reference)
);

CREATE INDEX idx_client_biometrics_client ON client_biometrics (client_id);


-- =====================================================
-- Auditoría
-- =====================================================

CREATE TABLE audit_logs (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID REFERENCES companies (id),
    user_id    UUID REFERENCES users (id),
    action     VARCHAR(50) NOT NULL,
    module     VARCHAR(50),
    entity     VARCHAR(50),
    entity_id  VARCHAR(64),
    detail     TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_audit_logs_company_created ON audit_logs (company_id, created_at);
CREATE INDEX idx_audit_logs_user_created    ON audit_logs (user_id, created_at);
CREATE INDEX idx_audit_logs_entity          ON audit_logs (entity, entity_id);

CREATE TABLE notifications (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id   UUID NOT NULL REFERENCES companies (id),
    client_id    UUID NOT NULL REFERENCES clients (id),
    type         VARCHAR(30) NOT NULL,
    channel      VARCHAR(20) NOT NULL,
    message      TEXT,
    scheduled_at TIMESTAMPTZ,
    sent_at      TIMESTAMPTZ,
    state        INTEGER NOT NULL DEFAULT 1,
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_notifications_company_state     ON notifications (company_id, state);
CREATE INDEX idx_notifications_client_scheduled  ON notifications (client_id, scheduled_at);


COMMIT;
