-- =====================================================
-- APEX GYM — Migración 003
-- 003_harden_users_auth.sql
--
-- Prerrequisito: 001_initial_schema.sql aplicado.
--
-- Objetivo:
--   1. Endurecer la nullability/defaults de `users` — las columnas de
--      autenticación pasan a NOT NULL (el backend ya las trata como
--      obligatorias, pero la BD no lo garantizaba).
--   2. Endurecer las columnas esenciales de `roles` (company-scoped).
--   3. Integridad multiempresa: impedir a nivel PostgreSQL que un usuario
--      de una empresa use un rol de OTRA empresa, incluso ejecutando SQL
--      manual fuera del backend.
--
-- Alcance controlado: SOLO `users`, `roles` y la integridad entre ambos.
-- No toca permissions, modules, companies, platform_admins ni otras tablas.
--
-- Sin DML de reparación: si en un entorno hay NULL o filas inconsistentes,
-- esta migración DEBE fallar (no inventa datos).
--
-- No idempotente (una migración se ejecuta una sola vez).
-- =====================================================

BEGIN;


-- =====================================================
-- Hardening de roles
-- =====================================================

ALTER TABLE roles ALTER COLUMN company_id SET NOT NULL;
ALTER TABLE roles ALTER COLUMN name       SET NOT NULL;

ALTER TABLE roles ALTER COLUMN state      SET DEFAULT 1;
ALTER TABLE roles ALTER COLUMN state      SET NOT NULL;

ALTER TABLE roles ALTER COLUMN created_at SET NOT NULL;
-- created_at conserva su DEFAULT NOW() de 001.
-- description permanece nullable.
-- roles.id sigue siendo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY.

-- Clave candidata (company_id, id) para poder referenciarla desde `users`
-- mediante una FOREIGN KEY compuesta. Es redundante para unicidad (id ya
-- es PK global) pero PostgreSQL exige una restricción UNIQUE/PK sobre las
-- columnas referenciadas por una FK compuesta.
ALTER TABLE roles
  ADD CONSTRAINT uq_roles_company_role_id UNIQUE (company_id, id);

-- uq_roles_company_name (UNIQUE (company_id, name)) se mantiene intacto.


-- =====================================================
-- Hardening de users
-- =====================================================

ALTER TABLE users ALTER COLUMN company_id SET NOT NULL;
ALTER TABLE users ALTER COLUMN username   SET NOT NULL;
ALTER TABLE users ALTER COLUMN full_name  SET NOT NULL;
ALTER TABLE users ALTER COLUMN password   SET NOT NULL;
ALTER TABLE users ALTER COLUMN role_id    SET NOT NULL;
ALTER TABLE users ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE users ALTER COLUMN state      SET DEFAULT 1;
ALTER TABLE users ALTER COLUMN state      SET NOT NULL;

-- Tipos sin cambios: id UUID PK DEFAULT gen_random_uuid(),
-- username VARCHAR, full_name VARCHAR(150), password VARCHAR(255).
-- created_at conserva su DEFAULT NOW() de 001.


-- =====================================================
-- Integridad multiempresa entre users y roles
-- =====================================================

-- Se reemplaza la FK simple users.role_id -> roles.id por una FK compuesta
-- (company_id, role_id) -> roles(company_id, id), que obliga a que el rol
-- asignado pertenezca a la MISMA empresa que el usuario.
ALTER TABLE users DROP CONSTRAINT users_role_id_fkey;

ALTER TABLE users
  ADD CONSTRAINT fk_users_company_role
  FOREIGN KEY (company_id, role_id)
  REFERENCES roles (company_id, id);
-- Sin ON DELETE / ON UPDATE: comportamiento estándar NO ACTION.

-- users.company_id -> companies.id (users_company_id_fkey) se mantiene.
-- users_pkey y uq_users_company_username se mantienen.
-- uq_users_company_username sigue siendo case-sensitive (deuda conocida:
-- el backend normaliza username con trim().toLowerCase(); una futura
-- migración podrá añadir UNIQUE (company_id, lower(username))).


COMMIT;
