import type { IsoDate } from "./calendar";
import { calculateExpirationDate, daysBetween } from "./calendar";
import type { MembershipType, MembershipTypeId } from "./membership";
import type { TrainerId } from "./trainer";

declare const clientIdBrand: unique symbol;

/** Identifies a client. Generated by the data layer, never by a component. */
export type ClientId = string & { readonly [clientIdBrand]: true };

export function toClientId(value: string): ClientId {
  return value as ClientId;
}

/**
 * The three client states defined in SRS §4.2.
 *
 * There is deliberately no "expiring soon" state: that is a derived view of the
 * expiration date, computed by {@link isExpiringSoon}. Storing it would let the
 * database drift out of sync with the calendar.
 *
 * There is also no "frozen" state — SRS §4.2 rules out pausing memberships.
 */
export type ClientStatus = "active" | "inactive" | "overdue";

/**
 * The blood types offered when registering a client.
 *
 * Free text on the backend (no CHECK constraint) — offered as a closed list
 * here so every client's record uses the same eight values, not near-misses
 * like "0+" or "A positivo".
 */
export const BLOOD_TYPES = [
  "A+",
  "A-",
  "B+",
  "B-",
  "AB+",
  "AB-",
  "O+",
  "O-",
] as const;

export type BloodType = (typeof BLOOD_TYPES)[number];

/** A gym client. */
export interface Client {
  readonly id: ClientId;
  readonly fullName: string;
  readonly idNumber: string;
  readonly phone: string;
  readonly email: string;
  readonly membershipTypeId: MembershipTypeId;
  readonly status: ClientStatus;
  /** Day the current membership began (RF-06). */
  readonly startDate: IsoDate;
  /** Derived from `startDate` and the membership term (RF-07). */
  readonly expirationDate: IsoDate;
  /**
   * Assigned trainer (RF-24). Present only on the personal and semi-personal
   * plans, which are the ones `requiresTrainer` identifies.
   */
  readonly trainerId?: TrainerId;
  readonly emergencyContactName: string;
  readonly emergencyContactPhone: string;
  readonly bloodType: string;
  /**
   * Set only at registration — the backend does not allow editing it
   * afterwards (`PATCH /clients/:id` has no `birthDate` field).
   */
  readonly birthDate?: IsoDate;
  readonly medicalCondition: string;
  /**
   * Si tiene foto, no cuál: el archivo lo nombra y lo sirve el servidor, y
   * quien pinta la fila solo necesita saber si pedirla.
   */
  readonly hasPhoto: boolean;
}

/**
 * Days a client may remain unpaid past expiry before turning overdue.
 *
 * OPEN QUESTION (SRS §8): the client has not defined whether a grace period
 * exists. Zero keeps the current behaviour literal — overdue the day after
 * expiry — and the value is a parameter so changing it is a one-line edit.
 */
export const DEFAULT_GRACE_DAYS = 0;

/** How many days remain before the membership expires. Negative once past due. */
export function daysUntilExpiration(
  client: Client,
  referenceDate: IsoDate,
): number {
  return daysBetween(referenceDate, client.expirationDate);
}

/**
 * The status the client should have on `referenceDate` (RF-21).
 *
 * A retired client stays inactive: lapsing is about payment, and someone who
 * already left has nothing to renew (SRS §4.5).
 */
export function resolveStatus(
  client: Client,
  referenceDate: IsoDate,
  graceDays: number = DEFAULT_GRACE_DAYS,
): ClientStatus {
  if (client.status === "inactive") {
    return "inactive";
  }
  const remaining = daysUntilExpiration(client, referenceDate);
  return remaining + graceDays < 0 ? "overdue" : "active";
}

/** Default window for the "expiring soon" view. */
export const EXPIRING_SOON_DAYS = 7;

/**
 * Whether the membership lapses within the next `withinDays` (RF-10 relies on
 * this to warn clients ahead of expiry).
 */
export function isExpiringSoon(
  client: Client,
  referenceDate: IsoDate,
  withinDays: number = EXPIRING_SOON_DAYS,
): boolean {
  if (resolveStatus(client, referenceDate) !== "active") {
    return false;
  }
  return expiresWithin(client.expirationDate, referenceDate, withinDays);
}

/**
 * Lo mismo, sobre una fecha suelta.
 *
 * El panel de ingreso no maneja `Client` entero: trae una vista de lectura con
 * el vencimiento y poco más. La regla de cuántos días cuentan como "pronto"
 * es una sola y vive aquí, no duplicada en cada pantalla que la pregunte.
 */
export function expiresWithin(
  expirationDate: IsoDate,
  referenceDate: IsoDate,
  withinDays: number = EXPIRING_SOON_DAYS,
): boolean {
  const remaining = daysBetween(referenceDate, expirationDate);
  return remaining >= 0 && remaining <= withinDays;
}

/** El aviso en español para una fecha de vencimiento suelta. */
export function noticeFor(
  expirationDate: IsoDate,
  referenceDate: IsoDate,
): string {
  const remaining = daysBetween(referenceDate, expirationDate);
  if (remaining < 0) return "Vencida";
  if (remaining === 0) return "Vence hoy";
  if (remaining === 1) return "Vence mañana";
  return `Vence en ${remaining} días`;
}

/**
 * Cómo está el cliente, para quien lo tiene enfrente.
 *
 * Es `ClientStatus` más "por vencer", que NO es un cuarto estado de §4.2: no
 * se guarda, se deduce de la fecha cada vez que se mira. Existe aparte porque
 * el mostrador necesita distinguir a quien está al día de quien lo estará
 * hasta el jueves, y `ClientStatus` responde "activo" a los dos.
 */
export type ClientStanding = ClientStatus | "expiringSoon";

export function resolveStanding(
  client: Client,
  referenceDate: IsoDate,
  withinDays: number = EXPIRING_SOON_DAYS,
): ClientStanding {
  const status = resolveStatus(client, referenceDate);
  if (status !== "active") return status;
  return isExpiringSoon(client, referenceDate, withinDays)
    ? "expiringSoon"
    : "active";
}

/**
 * Cuántos días le quedan, en español y ya redondeado.
 *
 * Vive aquí y no en el componente porque "hoy" y "mañana" son casos que
 * cambian la frase entera, no el formato: un `${dias} días` diría "0 días"
 * el mismo día del vencimiento.
 */
export function expiryNotice(client: Client, referenceDate: IsoDate): string {
  return noticeFor(client.expirationDate, referenceDate);
}

/** Marks a client as retired. No reason is required (SRS §4.5). */
export function retire(client: Client): Client {
  return { ...client, status: "inactive" };
}

/** The fields captured when registering a client. Id and expiry are derived. */
export type ClientDraft = Omit<Client, "id" | "expirationDate">;

/**
 * Builds a client, deriving the expiration date from the membership term
 * (RF-07). The id is supplied by the data layer, never by a component.
 */
export function createClient(
  id: ClientId,
  draft: ClientDraft,
  type: MembershipType,
): Client {
  return {
    ...draft,
    id,
    expirationDate: calculateExpirationDate(draft.startDate, type.term),
  };
}

/**
 * Re-derives the expiration date after a change of start date or plan (RF-07),
 * so the stored value can never drift from the term that produced it.
 */
export function withMembership(
  client: Client,
  type: MembershipType,
  startDate: IsoDate = client.startDate,
): Client {
  return {
    ...client,
    membershipTypeId: type.id,
    startDate,
    expirationDate: calculateExpirationDate(startDate, type.term),
  };
}

/**
 * Whether the client matches a free-text search over name, id number and phone.
 *
 * Lives in the domain rather than in the table component so it can be tested
 * without rendering, and reused by any future client picker.
 */
export function matchesQuery(client: Client, query: string): boolean {
  const needle = query.trim().toLowerCase();
  if (!needle) return true;

  return [client.fullName, client.idNumber, client.phone].some((field) =>
    field.toLowerCase().includes(needle),
  );
}
